version: '2'
services:
  indexd:
    image: "quay.io/cdis/indexd"
    volumes:
      - ./index_settings.py:/var/www/indexd/local_settings.py
    ports:
      - "8080:80"
    depends_on:
      - postgres
  user-api:
    image: "quay.io/cdis/user-api"
    volumes:
      - ./userapi_settings.py:/var/www/user-api/local_settings.py
    ports:
      - "8081:80"
    depends_on:
      - postgres
  gdcapi:
    image: "quay.io/cdis/gdcapi"
    volumes:
      - ./gdcapi_wsgi.py:/var/www/gdcapi/wsgi.py
    ports:
      - "8082:80"
    depends_on:
      - postgres
  dataportal:
    image: "quay.io/cdis/data-portal"
    ports:
      - "8083:80"
    depends_on:
      - postgres
  nginx:
    image: "nginx"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - indexd
      - user-api
      - gdcapi
      - dataportal
  postgres:
    image: postgres:9.6.1
    ports:
      - 5432:5432
    volumes:
      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
      - "/Users/heathap/projects/fauxcommons/bpa-replicate/bpa-pgdata:/var/lib/postgresql/data"
